name: CI
on:
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec
      - name: Rubocop
        run: bundle exec rubocop --parallel
